"""empty message

Revision ID: 4f82e9fa9c92
Revises: 9ab60b0c49f9
Create Date: 2024-03-22 15:43:55.824958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f82e9fa9c92'
down_revision: Union[str, None] = '9ab60b0c49f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
